### ISSUE TITLE
No longer works on mobile

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#85] opened 2020-08-09 13:46 UTC
While the page still works great on normal browsers...
It stopped working on mobile safari on e.g. my iPad. Could the recent right click zoom change be the issue?

**Comment by Senryoku** [comment] 2020-08-09 14:03
Indeed, I get a blank screen using Firefox on Android. Is this the same issue?
It load correctly on Chrome, and I don't have access to Safari or any iOS device to test it.

Unfortunately debugging on Android is only available on Firefox Nightly and the app loads just fine on this version... Debugging via USB is already a pain, I'm not sure what to do here.

**Comment by tooomm** [comment] 2020-08-09 14:22
Exactly, it shows a blank screen on Safari as well (iOS 12 and iOS 13)!

It works on FF Nightly on Android again? Hmm, maybe somebody can test on iOS 14?

**Comment by Senryoku** [comment] 2020-08-09 14:25
Regression is there since 4b1b444c2bf61a76b5e1075f80896775e2de3046

**Comment by Senryoku** [comment] 2020-08-09 15:00
Hopefully fixed by 2dcc43162fb9d8ad6900f59f423ec2f4c3d4363b

**Comment by tooomm** [comment] 2020-08-10 13:29
Fixed!

**Closed** 2020-08-10 13:31 UTC

**Comment by tooomm** [comment] 2020-09-07 21:43
Looks like it happens again 🙈

**Comment by Senryoku** [comment] 2020-09-07 22:51
Wup, my bad, I was careless when I merged the server and client version of the function... Should be fixed again by d166bae1f7704cae996fc2255a49b9f18392d44e

**Comment by tooomm** [comment] 2020-09-08 07:31
Works again 👍
