### ISSUE TITLE
Small display issue for timer and pick number on mobile

### ISSUE THREAD

**Issue by NicolasLevaique** [Senryoku/MTGADraft#61] opened 2020-07-11 10:52 UTC
After the first pick, display of the timer/pick number gets a little weird on mobile:

![image](https://user-images.githubusercontent.com/8191092/87222591-2a826500-c375-11ea-8a76-3b84b3cae8b4.png)

**Comment by Senryoku** [comment] 2020-07-11 12:31
Seems to only happen in Chrome; Font size (visually, no css rule change) gets bigger when the window's width is below 980px or so.
Doesn't happen anywhere else afaik.

**Comment by tooomm** [comment] 2020-08-11 12:23
Can confirm, in iOS 13 on mobile Safari I can not reproduce this.

**Comment by joesaraceno** [comment] 2020-09-12 17:11
I'm having trouble reproducing this in Chrome on mobile (Moto X) or in Chrome on desktop using mobile device settings. Even when the screen size is quite collapsed to try and force the width of the `#chrono` element to be really small. 

It almost looks like the flex-direction of the `booster-controls` container is currently different from this issues screenshot above. It's arranged like a column in my screenshot, but not due to a specific css rule that I could quickly find.

![image](https://user-images.githubusercontent.com/45146247/93000906-6dcd9100-f4e8-11ea-8de9-d23f8812d3c0.png)

**Comment by Senryoku** [comment] 2020-09-14 01:15
Cannot reproduce it either anymore (neither on desktop Chrome with device toolbar nor on an actual android device).
Closing this for now (there's another issue for general mobile UI improvement).

**Closed by Senryoku** 2020-09-14 01:15 UTC
Labels: bug, frontend
